language: php
php:
  - '7.1'
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - composer global require hirak/prestissimo
  - bash setup-dev.sh
script:
  - pwd
  - vendor/bin/behat
