language: php
php:
  - '7.1'
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - cp .ci/* .
  - composer global require hirak/prestissimo
  - composer global require behat/behat=^3.3
  - composer install
script:
  - pwd
  - ls -al
  - ls -al /home/travis/.composer/vendor/bin
  - /home/travis/.composer/vendor/bin/behat
