language: php
php:
  - '7.1'
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - composer global require hirak/prestissimo
  - composer install --quiet
  - composer require behat/behat=^3.3  behat/mink-extension=^2.2 behat/mink-goutte-driver=^1.2 behat/mink-selenium2-driver=^1.3 --quiet
script:
  - pwd
  - vendor/bin/behat
