language: php
php:
  - '7.1'
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - cp .ci/* .
  - composer global require hirak/prestissimo
  - composer require behat/behat=^3.3
  - composer require behat/mink-extension=^2.2
  - composer require behat/mink-goutte-driver=^1.2
  - composer require behat/mink-selenium2-driver=^1.3
  - composer install
script:
  - pwd
  - ls -al
  - ls -al vendor/bin
  - ls -al /home/travis/.composer/vendor/bin
  - vendor/bin/behat
