language: php
php:
  - '7.1'
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - cp .ci/* .
  - composer install
  - composer require behat/behat=^3.3
script:
  - vendor/.bin/behat
